### ISSUE TITLE
Add Touchpad config file

### ISSUE THREAD

**Issue by JorgeCepeda** [shalva97/kde-configuration-files#11]
.config/touchpadxlibinputrc

**Comment by shalva97** [comment]
Hi, its been a long time I have not used KDE. Can you send a PR on this?

**Comment by chxei** [comment]
I can confirm thats the correct file on x11, done some testing. Can't tell enything about wayland. Can anyone tell that the file is the same for wayland?

**Comment by MenacingPerson** [comment]
The file is ~/.config/kcminputrc on wayland.

**Comment by shalva97** [comment]
just merged the PR so will close this
