### ISSUE TITLE
do you aware any system default config file?

### ISSUE THREAD

**Issue by braindevices** [shalva97/kde-configuration-files#16]
so far in ubuntu 20.04 my KDE apps are following the gnome system setting. I cannot find any of your theme related settings in my ~/.config or ~/.local. Do you aware if  there is some place to set those values system wide? I tried kreadconfig5, it is useless and cannot give me any system default value.

**Comment by chxei** [comment]
> my KDE apps are following the gnome system setting 

@braindevices  Assuming you are using a gnome desktop, which we are unfamiliar with. This repo refers KDE as a desktop environment. KDE apps are just ordinary apps built with the QT framework. This is out of the scope of this repo.  Maybe you try to use Kvantum to manage how QT apps look on other DEs.

**Comment by shalva97** [comment]
Its been a while, will close this ticket. If there questions you may reopen it...
