### ISSUE TITLE
KDE plasma ignores settings set in files but still changes based on GUI

### ISSUE THREAD

**Issue by hainguyen1107** [shalva97/kde-configuration-files#23]
I used some of your commands to change the settings of KDE plasma! I confirm that the config file content has changed according to the command!
However, somehow Plasma still not changes accordingly to the changes in config files even after reboot!
If you have any solution, pls share it! thank you so much!

**Comment by chxei** [comment]
Is it some of commands that don't work or nothing works?

**Comment by hainguyen1107** [comment]
Thank you for your reply! 
After wasting time trying to figure out what's wrong with it... I gave up that hopeless dream and decided to re-install the whole new arch linux + KDE!
Somehow it works perfectly this time @@
Anyway, can you show me how to configure KDE to automatically show hidden files? 
I tried to change 'kdeglobals' - 'KFileDialog Settings' - 'Show hidden files=true' but it did not work at all.
I would appreciate any documentation too!
Thank you :D

**Comment by chxei** [comment]
I guess you want to show hidden files in Dolphin. you are changing hidden file settings in the file picker.
try this: `~/.local/share/dolphin/view_properties/global/.directory`


[Settings]
HiddenFilesShown=true

**Comment by hainguyen1107** [comment]
Oh nice! Stupid me! Thank you so much!
